
"""

Django settings for proyecto project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from pymongo import MongoClient


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-(7!$grm(8@rif$#fis)a9x^nv)^i_ke*&lywu=iws05nh-^lpq"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "tienda",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "proyecto.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "tienda.context_processors.carrito_context",
            ],
        },
    },
]

WSGI_APPLICATION = "proyecto.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'tienda_abarrotes',  # Aquí puedes poner el nombre que quieras para tu base de datos
        'CLIENT': {
            'host': 'mongodb://localhost:27017',
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

LOGIN_URL = "/index"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Conexión a MongoDB
try:
    MONGO_CLIENT = MongoClient("localhost", 27017)

    # 1. Cambiamos 'proyecto_python' por 'tienda_abarrotes' (para que coincida con DATABASES)
    MONGO_DB = MONGO_CLIENT["tienda_abarrotes"]

    # 2. Cambiamos 'usuarios' por 'auth_user' (donde Django guarda los usuarios)
    MONGO_COLLECTION = MONGO_DB["auth_user"]

    PRODUCTOS_COLLECTION = MONGO_DB["productos"]
    CARRITOS_COLLECTION = MONGO_DB["carritos"]
    ORDENES_COLLECTION = MONGO_DB["ordenes"]
    LISTA_DESEOS_COLLECTION = MONGO_DB["lista_deseos"]
    DIRECCIONES_COLLECTION = MONGO_DB["direcciones"]
    CONFIGURACION_COLLECTION = MONGO_DB["configuracion_usuarios"]
    CITAS_COLLECTION = MONGO_DB["citas"]
    TIENDAS_COLLECTION = MONGO_DB["tiendas"]

    print("Conexión exitosa a MongoDB (tienda_abarrotes)")

except Exception as ex:
    print("Error al conectar: {}".format(ex))

except Exception as ex:
    print("Error al conectar: {}".format(ex))


# settings.py
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"  # o 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 semanas en segundos
SESSION_SAVE_EVERY_REQUEST = True  # IMPORTANTE: Guarda sesión en cada request
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Si usas signed_cookies, asegúrate de tener:
SESSION_COOKIE_SECURE = False  # True en producción con HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
